version: "3.9" # Use a recent version of docker-compose
services:
  app:
    build: .
    ports:
      - "8000:3000"
    volumes:
      - .:/app # Mount current directory to /app in the container
      - /app/node_modules # Important: Exclude node_modules from volume to avoid conflicts
    environment: # Important for nodemon to work correctly
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/UsersData # Add MongoDB URL to environment variables
      - REDIS_URL=redis://redis:6379
      - Base_URL=http://localhost
      - Expose_PORT=8000
    command: sh -c "npm install && npm run dev" # Install dependencies and run nodemon in the container
    container_name: BE # Give a name to the container for easy management
    depends_on:
      - mongo # Ensure MongoDB is started before the app
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo # Give a name to the MongoDB container
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
    networks:
      - app-network



volumes:
  mongo-data:

networks:
  app-network: