name: Docker Build and Test

on:
  push: {}  # 每次 commit 都會觸發
  # schedule:
  #   - cron: '0 */4 * * *'  # 每四小時觸發一次

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy backend with docker-compose
        working-directory: backend
        run: |
          docker-compose up -d

      - name: Build frontend image
        working-directory: frontend
        run: |
          docker build -t frontend --build-arg NAME=frontend .

      - name: Run frontend container
        run: |
          docker run -d -p 5173:5173 --name URL_FE frontend

      - name: Display access URL message
        run: |
          echo "access url shorten service at http://localhost:5173"

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          wget -N https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          rm chromedriver_linux64.zip

      - name: Test frontend
        working-directory: testing/selenium_test
        run: |
          pip install selenium
          python main.py

